# @prettier

# build settings

repository: mozgbrasil/mozgbrasil.github.io

versao: 13/07/2018 17:15:24

# theme: jekyll-theme-minimal
# theme: jekyll-theme-modernist
# remote_theme: jekyll-theme-mozg
# remote_theme: mozgbrasil/jekyll-theme-mozg

layout: default

markdown: kramdown
highlighter: rouge

#kramdown:
#auto_ids: true

include: [".htaccess"]

exclude: [
    "403.html",
    "404.html",
    "script",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "README.md",
    "node_modules"
  ] # , "bower_components", "bower.json", "node_modules", "package.json", "vendor"

sass:
  style: :compressed
  # Where you keep your scss files
  #sass_dir: assets/css/
  # Where sass should look for other scss
  #load_paths:
  #- node_modules/

plugins:
  [
    "jekyll-mentions",
    "jekyll-github-metadata",
    "jekyll-seo-tag",
    "jekyll-paginate",
    "jekyll-avatar"
  ]

# plugins: jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

twitter:
  username: mozgbrasil

facebook:
  app_id: 190289028000894 # https://developers.facebook.com/
  publisher: 190289028000894
  admins: 190289028000894

social:
  name: Mozg Brasil
  links:
    - https://twitter.com/mozgbrasil
    - https://www.facebook.com/mozgbrasil
    - https://www.linkedin.com/in/mozgbrasil
    - https://plus.google.com/117178438811960262290
    - https://github.com/mozgbrasil
    - https://keybase.io/mozgbrasil

webmaster_verifications:
  google: google7b4e5e32dda0c66d

# --

redcarpet:
  extensions:
    [
      "no_intra_emphasis",
      "fenced_code_blocks",
      "autolink",
      "tables",
      "with_toc_data"
    ]

paginate: 30
paginate_path: "page:num"

permalink: /:categories/:title
excerpt_separator: "[-----]"

# site settings

# mode: dev | production
url: http://mozg.com.br
mode: production
devurl: http://127.0.0.1:4000
baseurl: "" # the subpath of your site, e.g. /blog/
title: MOZG
tagline: Desenvolvedor de softwares
description: > # this means to ignore newlines until "baseurl:"
  Este projeto foi criado por Marcio dos Santos Amorim, desenvolvedor de softwares desde 1999 / Atendimento de Segunda-Feira à Sexta-Feira, 09:00 às 12:00 e 14:00 às 18:00 / suporte@mozg.com.br

email: suporte@mozg.com.br
github_username: mozgbrasil
facebook_username: mozgbrasil
plusgoogle_username: mozgbrasil
youtube_username: mozgbrasil

top_menu: snippet-top-menu-2.html

# API Keys.

google_api_key: "AIzaSyBngTQOddD3rxUGFNsh4JSC5gkEJPGo6BQ" # https://code.google.com/apis/console/ -> Project Name -> APIs -> Credenciais
google_cse_id: "013400461319534586214:elspbzci0nc" # https://cse.google.com/ -> Google Custom Search Engine unique id
google_analytics_ua: "UA-73869264-1" # https://www.google.com/analytics/web/ -> Google Analytics site specific id

# Embeds

google_map_zoom: 16 # 1=Global zoom 18=Street Level
google_map_view: satellite # hybrid | satellite | roadmap
google_map_height: 450 # Default map height. Width adjusts to container.

# Fix: GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.

github: [metadata]
